// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lyapunov_cpp
Rcpp::List lyapunov_cpp(const arma::mat& Tm, const arma::mat& W, int max_iter, double tol);
RcppExport SEXP _qpmR_lyapunov_cpp(SEXP TmSEXP, SEXP WSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Tm(TmSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(lyapunov_cpp(Tm, W, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// kalman_loglik_cpp
Rcpp::List kalman_loglik_cpp(const arma::mat& Tt, const arma::mat& RQR, const arma::mat& Z, const arma::vec& d, const arma::mat& H, const arma::mat& P1, const arma::mat& Y);
RcppExport SEXP _qpmR_kalman_loglik_cpp(SEXP TtSEXP, SEXP RQRSEXP, SEXP ZSEXP, SEXP dSEXP, SEXP HSEXP, SEXP P1SEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Tt(TtSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type RQR(RQRSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P1(P1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(kalman_loglik_cpp(Tt, RQR, Z, d, H, P1, Y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_qpmR_lyapunov_cpp", (DL_FUNC) &_qpmR_lyapunov_cpp, 4},
    {"_qpmR_kalman_loglik_cpp", (DL_FUNC) &_qpmR_kalman_loglik_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_qpmR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
