# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lyapunov_cpp <- function(Tm, W, max_iter = 60L, tol = 1e-14) {
    .Call(`_qpmR_lyapunov_cpp`, Tm, W, max_iter, tol)
}

kalman_loglik_cpp <- function(Tt, RQR, Z, d, H, P1, Y) {
    .Call(`_qpmR_kalman_loglik_cpp`, Tt, RQR, Z, d, H, P1, Y)
}

